apiVersion: v1
kind: Service
metadata:
  name: auction-bidding-app-service
spec:
  selector:
    app: auction-bidding-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
